config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'
  resource :dashboards, only: %i[new show create]
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@mybusiness.com\z/
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
    scope :gross_income_by_sales_data , -> { group('date(created_at)').sum('item_price * purchase_count') }
    scope :total_all_time_gross_income , -> { sum('item_price * purchase_count') }
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    admin = Admin.from_google(from_google_params)

    if admin.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect admin, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_admin_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_admin_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    new_admin_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_admin!
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true
require_relative '../domain/deliveries/manager_deliveries'

class DashboardsController < ApplicationController
  def show
    manager_deliveries = Deliveries::ManagerDeliveries.new
    @gross_income_by_sales_data = manager_deliveries.gross_income_by_sales_data
    @total_all_time_gross_income = manager_deliveries.total_all_time_gross_income
  end

  def new
  end

  def create
    begin
      ProcessingDeliveriesByFile.call(parser_params["file_data"])
      render :show
    rescue StandardError => e
      Rails.logger.info("Delivery create request error: #{e.message}")
      raise e
    end
  end

  private

  def parser_params
    params.require(:parser).permit(:file_data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Delivery::DeliveryHelper
end

app/helpers/delivery/delivery_helper.rb
module Delivery::DeliveryHelper
    def gross_income_type
        {deliver_date: 0, total_item_price: 1}
    end
end

app/views/dashboards/_detail_gross_income.html.erb
<% details.each do |gross_income| %>
    <tr>
        <th scope="row">-</th>
        <td><%= gross_income[gross_income_type[:deliver_date]] %></td>
        <td><%= gross_income[gross_income_type[:total_item_price]] %></td>
    </tr>
<% end %>

app/views/dashboards/_grid_gross_income.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Sales date</th>
      <th scope="col">Gross income</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "detail_gross_income", locals: {details: details} %>
    <%= render partial: "totalizer_gross_income", locals: {totalizer: totalizer}%>   
  </tbody>
</table>

app/views/dashboards/_totalizer_gross_income.html.erb
<tr>
    <td></td>
    <td></td>
    <td>Total: <%= totalizer %></td>
</tr>

app/views/dashboards/new.html.erb
<div class="d-flex justify-content-center">
    <div class="d-flex flex-column">
        <p class="fs-1">Parse deliveries by file</p>

        <%= form_for :parser, url: "/dashboards", multipart: true, method: :post do |form| %>
            <div class="d-flex flex-column">
                <div class="d-flex flex-row"> 
                    <div class="p-2 flex-grow-1">
                        <%= form.label :file_data, "Where is your file/data:" %>
                    </div>
                </div>

                <div class="d-flex flex-row mb-5">                    
                    <div class="p-2 flex-grow-1">
                        <%= form.file_field :file_data %>
                    </div>
                </div>
            </div>

            <%= form.submit "Parse Data" %>
            <%= link_to "Back", dashboards_path %>
        <% end %>
    </div>
</div>

app/views/dashboards/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8"><h1>Deliveries sales dashboard</h1></div>
        <div class="col2"></div>
    </div>

    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="d-flex flex-row justify-content-center">
                <%= render partial: "grid_gross_income",
                    locals: {details: @gross_income_by_sales_data,
                            totalizer: @total_all_time_gross_income}
                %>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>

<div class="d-flex flex-row justify-content-center">
    <div class="p-2">
        <%= link_to "Process deliveries by file", new_dashboards_url %>
    </div>
    <div class="p-2">
        <%= link_to "Sign Out", destroy_admin_session_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleOauthDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>

    <%= yield %>
  </body>
</html>